<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>scopeName</key>
        <string>testent-vscode-extension.output</string>
        <key>name</key>
        <string>testent-vscode-extension-output</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>token.info-token</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>string</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(^\[Running\])(.*)</string>
                <key>name</key>
                <string>code-runner.running</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>token.info-token</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>string</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>token.debug-token</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(^\[Done\])(.+)(?:(code=0)|(code=\d+))</string>
                <key>name</key>
                <string>code-runner.done</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>token.info-token</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(^Function inputs:)</string>
                <key>name</key>
                <string>code-runner.inputsheader</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>token.info-token</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(^Function output:)</string>
                <key>name</key>
                <string>code-runner.outputheader</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>token.error-token</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(^Function throws an exception:)</string>
                <key>name</key>
                <string>code-runner.exceptionheader</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>string</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(^Class:)</string>
                <key>name</key>
                <string>code-runner.expectionclass</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>string</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(^Message:)</string>
                <key>name</key>
                <string>code-runner.expectionmessage</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>string</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(^\S+:  )</string>
                <key>name</key>
                <string>code-runner.input</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(^===== Input set number \d =====)</string>
                <key>name</key>
                <string>code-runner.inputsetheader</string>
            </dict>
        </array>
    </dict>
</plist>